### ISSUE TITLE
文章最后未提出解决方案

### ISSUE THREAD

**Issue by aozhimin** [aozhimin/iOS-Debug-Hacks#2]

**Comment by aozhimin** [comment]
@ZenonHuang 昨天有些地方可能没有讲清楚，文章其实就是没有给出解决问题的解决方案，我后面回头再去看你昨天那条 Issue 才发现，解决方案不是将使用 Aspects 库的地方去掉就不管了，而是替换成通过 Method Swizzling 的方式来直接换掉我想要 Hook Selector，当然你提到 Fork Aspects 库自己去修改也是一个思路，但是这种方式侵入性比较大，牵涉到修改三方库，成本较高，所以最后还是选择前面这个方式，但这个过程我没写入文章中，所以对你造成了误导，我会把这部分写入文章结尾。

**Comment by ZenonHuang** [comment]
很负责，期待更新 ：）

**Comment by aozhimin** [comment]
@ZenonHuang 文章已更新 :)
